// test-auth.js
const http = require("http");

// Helper function to send HTTP requests using Node's native module
function sendRequest(path, data) {
  return new Promise((resolve, reject) => {
    const jsonData = JSON.stringify(data);
    const options = {
      hostname: "localhost",
      port: 5000,
      path: path,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(jsonData),
      },
    };

    const req = http.request(options, (res) => {
      let body = "";
      res.on("data", (chunk) => (body += chunk));
      res.on("end", () => {
        try {
          resolve({ statusCode: res.statusCode, data: JSON.parse(body) });
        } catch (e) {
          resolve({ statusCode: res.statusCode, data: body });
        }
      });
    });

    req.on("error", (err) => reject(err));
    req.write(jsonData);
    req.end();
  });
}

async function runTest() {
  console.log("🚀 Starting Automated API Authentication Tests...\n");

  // Generate a random username variation so we can rerun this test without manual deletions
  const testUser = {
    username: `dev_rajini_${Math.floor(Math.random() * 1000)}`,
    email: `rajini_${Math.floor(Math.random() * 1000)}@codefolio.com`,
    password: "SecurePassword123",
    name: "Rajini",
  };

  try {
    // 1. TEST REGISTER ENDPOINT
    console.log(`⏳ Testing Registration for username: ${testUser.username}...`);
    const regResult = await sendRequest("/api/auth/register", testUser);
    console.log(`Status: ${regResult.statusCode}`);
    console.log(`Response:`, regResult.data, "\n");

    if (regResult.statusCode !== 201) {
      console.log("❌ Registration test failed. Stopping workflow.");
      return;
    }

    // 2. TEST LOGIN ENDPOINT
    console.log(`⏳ Testing Login with email: ${testUser.email}...`);
    const loginResult = await sendRequest("/api/auth/login", {
      email: testUser.email,
      password: testUser.password,
    });
    console.log(`Status: ${loginResult.statusCode}`);
    console.log(`Response:`, loginResult.data, "\n");

    if (loginResult.statusCode === 200 && loginResult.data.token) {
      console.log("🎉 SUCCESS! Registration and Login work perfectly!");
      console.log("🔒 JWT Session token successfully generated by your server.");
    } else {
      console.log("❌ Login test failed.");
    }
  } catch (error) {
    console.error("💥 Test runner error:", error.message);
    console.log("\n💡 Make sure your main server is running (`node server.js`) in another terminal window!");
  }
}

runTest();
